[package]
name = "neuralkit"
version = "0.1.0"
edition = "2024"
description = "A simple neural network toolkit / building blocks for neural networks in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/neuralkit-ai/neuralkit"
readme = "README.md"
keywords = ["QML"]
categories = ["machine-learning", "science"]
authors = ["R. <r@neuralkit.ai>"]

[dependencies]